version: "3"
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "80:8080"
    volumes:
      - .:/pocketistic/
    depends_on:
      - "db"

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      - POSTGRES_DB=pocketistic
      - POSTGRES_PASSWORD=1234567890
