version: '2'
services:
    frontend:
        build: ./frontend
        ports:
            - 9000:9000
        volumes:
            - ./frontend:/frontend
    backend:
        build: ./backend
        ports:
            - 8080:8080
        volumes:
            - ./backend:/backend
